(print (append))
(print (append 'a))
(print (append '(a b)))
(print (append '(a b) '(c d)))
(print (append '(a b) '(c d) () nil '(e f)))
(print (append () '(a b)))
(print (append nil '(a b)))
(print (append '(a b) 'c))
(print (append () 'c))
;(print (append '(a b) 'c 'd))
