(print (symbolp 'foo))
(print (symbolp 1))
(print (symbolp nil))
(print (symbolp '()))
(print (symbolp "foo"))
(print "====")
(print (stringp "foo"))
(print (stringp 'foo))
(print "====")
(print (consp (cons 1 2)))
(print (consp '(1 2)))
(print (consp nil))
