(print (symbolp 'foo))
(print (symbolp 1))
(print (symbolp nil))
(print (symbolp '()))
(print (symbolp "foo"))
(print "====")
(print (stringp "foo"))
(print (stringp 'foo))
(print "====")
(print (consp (cons 1 2)))
(print (consp '(1 2)))
(print (consp nil))
(print "====")
(print (atom 'foo))
(print (atom 12))
(print (atom (list  1 2)))
(print (atom '()))
(print (atom nil))
(print "====")
(print (listp (cons 1 2)))
(print (listp '(1 2)))
(print (listp nil))
(print (listp 1))
